import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "flowbite"
import "./globals.css";
import { Providers } from "./providers";
import Navbar from "./components/layout/Navbar"
import Footer from "./components/layout/Footer";
import LoginModal from "./components/loginModal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <Providers>
          <LoginModal/>
          <Navbar/>
          {children}
          <Footer/>
          </Providers>
      </body>
    </html>
  );
}
